import LegalPagesWrapper from "@/components/legal-pages-wrapper"
import Link from "next/link"

export default function TermsPage() {
  return (
    <LegalPagesWrapper>
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500">Effective: March 21, 2025</p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-8">
        <h2 className="text-lg font-semibold text-amber-800 mb-2">IMPORTANT NOTICE REGARDING YOUR LEGAL RIGHTS</h2>
        <p className="text-amber-700">
          PLEASE READ THESE TERMS OF SERVICE CAREFULLY. THEY CONTAIN AN ARBITRATION AGREEMENT AND CLASS ACTION WAIVER
          THAT AFFECT YOUR LEGAL RIGHTS.
        </p>
        <p className="text-amber-700 mt-2">
          By accessing or using the Services provided by Financial Planner AI, LLC, you acknowledge that you have read,
          understood, and agree to be bound by these Terms of Service, including the binding arbitration provision and
          class action waiver found in Section 12.
        </p>
      </div>

      <section id="introduction">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">1. INTRODUCTION AND ACCEPTANCE</h2>
        <p className="mb-4">
          Welcome to PawSense AI. These Terms of Service (the "Terms") constitute a legally binding agreement between
          you and Financial Planner AI, LLC, a limited liability company organized under the laws of New Jersey
          ("Financial Planner AI," "we," "our," or "us"). These Terms govern your access to and use of our website
          located at https://www.pawsense-ai.com (the "Website"), our proprietary web-based software application (the
          "Application"), our AI-powered analysis feature ("PawSense AI"), our chatbot service, and all related services
          (collectively, the "Services").
        </p>
        <p className="mb-4">
          These Terms incorporate by reference our{" "}
          <Link href="/privacy" className="text-[#2980b9] hover:underline">
            Privacy Policy
          </Link>
          , available at https://www.pawsense-ai.com/privacy, our{" "}
          <Link href="/cookie-policy" className="text-[#2980b9] hover:underline">
            Cookie Policy
          </Link>{" "}
          https://www.pawsense-ai.com/cookie-policy and any additional terms, conditions, or policies we may provide to
          you from time to time.
        </p>
        <p>
          By accessing or using our Services, you represent and warrant that you have read, understood, and agree to be
          bound by these Terms. If you don't agree to these Terms in their entirety, you must not access or use our
          Services.
        </p>
      </section>

      <section id="definitions">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">2. DEFINITIONS AND INTERPRETATION</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">
          2.1 Throughout these Terms, the following definitions apply:
        </h3>
        <p className="mb-2">
          <span className="font-medium">"Affiliate"</span> means any entity that directly or indirectly controls, is
          controlled by, or is under common control with Financial Planner AI, where "control" means the ownership of,
          or the power to vote, at least fifty percent (50%) of the voting stock, shares or interests of such entity.
        </p>
        <p className="mb-2">
          <span className="font-medium">"AI Technology"</span> means our artificial intelligence and machine learning
          technologies, algorithms, models, and systems used to provide the Services.
        </p>
        <p className="mb-4">
          <span className="font-medium">"Analyses"</span> means the outputs, reports, summaries, and other materials
          generated by our AI Technology based on the information and documentation you provide.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">2.2 In these Terms:</h3>
        <p className="mb-1">
          (a) the words "include," "includes," and "including" are deemed to be followed by the words "without
          limitation";
        </p>
        <p className="mb-1">(b) the word "or" is not exclusive;</p>
        <p className="mb-1">
          (c) the words "herein," "hereof," "hereby," "hereto," and "hereunder" refer to these Terms as a whole; and
        </p>
        <p>(d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa.</p>
      </section>

      {/* Additional sections would continue in the same format */}

      {/* Contact Information Section */}
      <section id="contact" className="mt-12 border-t pt-8">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9]">17. CONTACT INFORMATION</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">17.1 General Inquiries</h3>
        <p className="mb-4">For general inquiries about the Services or these Terms, please contact us at:</p>
        <p className="mb-1">Financial Planner AI, LLC</p>
        <p className="mb-4">rpc@financialplanner-ai.com</p>

        <h3 className="text-lg font-semibold mt-4 mb-2">17.2 Legal Notices</h3>
        <p className="mb-4">For legal notices, please contact us at:</p>
        <p className="mb-1">Financial Planner AI, LLC</p>
        <p className="mb-1">Attn: Legal Matter</p>
        <p className="mb-1">155 Glendale Drive</p>
        <p className="mb-1">Freehold, NJ 07728</p>
        <p>rpc@financialplanner-ai.com</p>
      </section>

      <div className="text-center text-sm text-gray-500 mt-12 pt-8 border-t">
        <p>Last Updated: March 21, 2025</p>
        <p>© 2025 Financial Planner AI, LLC. All rights reserved.</p>
      </div>
    </LegalPagesWrapper>
  )
}

