import LegalPagesWrapper from "../components/legal-pages-wrapper"
import Link from "next/link"

export default function TermsPage() {
  return (
    <LegalPagesWrapper>
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500">Effective: March 21, 2025</p>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-8">
        <h2 className="text-lg font-semibold text-amber-800 mb-2">IMPORTANT NOTICE REGARDING YOUR LEGAL RIGHTS</h2>
        <p className="text-amber-700">
          PLEASE READ THESE TERMS OF SERVICE CAREFULLY. THEY CONTAIN AN ARBITRATION AGREEMENT AND CLASS ACTION WAIVER
          THAT AFFECT YOUR LEGAL RIGHTS.
        </p>
        <p className="text-amber-700 mt-2">
          By accessing or using the Services provided by Financial Planner AI, LLC, you acknowledge that you have read,
          understood, and agree to be bound by these Terms of Service, including the binding arbitration provision and
          class action waiver found in Section 12.
        </p>
      </div>

      <section id="introduction">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">1. INTRODUCTION AND ACCEPTANCE</h2>
        <p className="mb-4">
          Welcome to PawSense AI. These Terms of Service (the "Terms") constitute a legally binding agreement between
          you and Financial Planner AI, LLC, a limited liability company organized under the laws of New Jersey
          ("Financial Planner AI," "we," "our," or "us"). These Terms govern your access to and use of our website
          located at https://www.pawsense-ai.com (the "Website"), our proprietary web-based software application (the
          "Application"), our AI-powered analysis feature ("PawSense AI"), our chatbot service, and all related services
          (collectively, the "Services").
        </p>
        <p className="mb-4">
          These Terms incorporate by reference our{" "}
          <Link href="/privacy" className="text-[#2980b9] hover:underline">
            Privacy Policy
          </Link>
          , available at https://www.pawsense-ai.com/privacy, our{" "}
          <Link href="/cookie-policy" className="text-[#2980b9] hover:underline">
            Cookie Policy
          </Link>{" "}
          https://www.pawsense-ai.com/cookie-policy and any additional terms, conditions, or policies we may provide to
          you from time to time.
        </p>
        <p>
          By accessing or using our Services, you represent and warrant that you have read, understood, and agree to be
          bound by these Terms. If you don't agree to these Terms in their entirety, you must not access or use our
          Services.
        </p>
      </section>

      <section id="definitions">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">2. DEFINITIONS AND INTERPRETATION</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">
          2.1 Throughout these Terms, the following definitions apply:
        </h3>
        <p className="mb-2">
          <span className="font-medium">"Affiliate"</span> means any entity that directly or indirectly controls, is
          controlled by, or is under common control with Financial Planner AI, where "control" means the ownership of,
          or the power to vote, at least fifty percent (50%) of the voting stock, shares or interests of such entity.
        </p>
        <p className="mb-2">
          <span className="font-medium">"AI Technology"</span> means our artificial intelligence and machine learning
          technologies, algorithms, models, and systems used to provide the Services.
        </p>
        <p className="mb-4">
          <span className="font-medium">"Analyses"</span> means the outputs, reports, summaries, and other materials
          generated by our AI Technology based on the information and documentation you provide.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">2.2 In these Terms:</h3>
        <p className="mb-1">
          (a) the words "include," "includes," and "including" are deemed to be followed by the words "without
          limitation";
        </p>
        <p className="mb-1">(b) the word "or" is not exclusive;</p>
        <p className="mb-1">
          (c) the words "herein," "hereof," "hereby," "hereto," and "hereunder" refer to these Terms as a whole; and
        </p>
        <p>(d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa.</p>
      </section>

      <section id="eligibility">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">3. ELIGIBILITY AND REGISTRATION</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">3.1 Eligibility Requirements</h3>
        <p className="mb-4">
          To access and use our Services, you must be at least eighteen (18) years old and have the legal capacity to
          form a binding contract with Financial Planner AI under applicable law.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">3.2 Registration Process</h3>
        <p className="mb-4">
          To access certain features of our Services, you must register for an account. When registering, you agree to
          provide accurate, current, and complete information about yourself as prompted by our registration process.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">3.3 Account Security</h3>
        <p className="mb-4">
          You are responsible for maintaining the confidentiality of your account credentials, including your username
          and password. You agree to notify us immediately of any unauthorized use of your account or any other breach
          of security.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">3.4 Account Types</h3>
        <p>
          Our Services may offer different types of accounts with varying features and functionality. The specific
          features and functionality available to you will depend on the type of account you register for and maintain.
        </p>
      </section>

      <section id="service-description">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">4. SERVICE DESCRIPTION AND SCOPE</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">4.1 Core Services</h3>
        <p className="mb-4">
          PawSense AI provides a web-based software application that enables dog owners to conduct dog behavior analyses
          through our proprietary AI Technology, which processes videos of dog behavior to provide insights and
          recommendations.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">4.2 Service Delivery</h3>
        <p className="mb-4">
          We will make the Services available to you pursuant to these Terms and any applicable Documentation. We may
          modify, enhance, or otherwise change the Services at any time in our sole discretion.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">4.3 Service Access</h3>
        <p>
          Subject to your compliance with these Terms and payment of applicable fees, we grant you a limited,
          non-exclusive, non-transferable, non-sublicensable right to access and use the Services solely for your
          internal business or personal purposes during the term of these Terms.
        </p>
      </section>

      <section id="limitations">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9] border-b pb-2">5. CRITICAL LIMITATIONS AND DISCLAIMERS</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">5.1 No Professional Advice</h3>
        <p className="mb-4 font-semibold">
          YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT THE SERVICES DO NOT CONSTITUTE PROFESSIONAL ADVICE OF ANY KIND.
        </p>
        <p className="mb-4">
          The Services are informational tools only and are not intended to replace the advice or services of licensed
          professionals. Financial Planner AI does not provide veterinary, behavioral, training, or other professional
          dog-related advice. We do not recommend, endorse, or sell any dog training products, methods, or services.
        </p>
        <p className="mb-4">
          You must consult with qualified professional advisors (such as veterinarians, certified dog trainers, or
          animal behaviorists) before making any decisions about your dog's care or training or taking any actions based
          on information provided through our Services. The Analyses generated by our Services are intended solely as
          starting points for discussions with your professional advisors and should never be relied upon as the sole
          basis for any decision or action regarding your dog's behavior, training, or health.
        </p>

        <h3 className="text-lg font-semibold mt-4 mb-2">5.2 AI Technology Limitations</h3>
        <p className="mb-4">
          You expressly acknowledge and understand that our Services utilize automated artificial intelligence and
          machine learning technologies that have inherent limitations and potential for error. The accuracy and
          reliability of our Analyses depend entirely on the quality, completeness, and accuracy of the information and
          videos you provide.
        </p>
        <p className="mb-4">Our AI Technology:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>May contain errors, bugs, or inaccuracies;</li>
          <li>May not capture all relevant factors or considerations;</li>
          <li>May produce inconsistent or unexpected results;</li>
          <li>Requires human review and professional verification;</li>
          <li>Is subject to regular updates that may affect results;</li>
          <li>Cannot verify the completeness or accuracy of input data;</li>
          <li>May have biases or limitations we have not identified; and</li>
          <li>Should never be relied upon without independent verification.</li>
        </ul>

        <h3 className="text-lg font-semibold mt-4 mb-2">5.3 Video Processing Restrictions</h3>
        <p className="mb-4">
          The Services are designed to process only dog behavior videos. We do not analyze other types of videos or
          content. You acknowledge and agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>We cannot verify the completeness, accuracy, or authenticity of any video you submit;</li>
          <li>
            The accuracy of our Analyses depends entirely on the quality, clarity, and content of the video provided;
          </li>
          <li>We do not independently verify any behavior or context shown in videos;</li>
          <li>Certain video formats or types may not be compatible with our Services;</li>
          <li>Processing errors or failures may occur due to video quality, format, length, or content issues; and</li>
          <li>We are not responsible for any errors or omissions in the videos you provide.</li>
        </ul>

        <h3 className="text-lg font-semibold mt-4 mb-2">5.4 Video Storage and Transmission</h3>
        <p className="mb-4">You acknowledge and understand that:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>
            Videos you upload are transmitted securely to our AI analysis partners, including Twelve Labs, OpenAI, and
            Anthropic;
          </li>
          <li>We do not permanently store the binary video files on our servers;</li>
          <li>Video data is processed by our AI partners to extract behavioral analysis information;</li>
          <li>
            After analysis, the original video is deleted from our AI partners' systems according to their respective
            data retention policies;
          </li>
          <li>
            The analysis results derived from your videos are retained in our system to provide you with insights and
            recommendations.
          </li>
        </ul>
      </section>

      <section id="contact" className="mt-12 border-t pt-8">
        <h2 className="text-xl font-bold mb-4 text-[#2980b9]">17. CONTACT INFORMATION</h2>

        <h3 className="text-lg font-semibold mt-4 mb-2">17.1 General Inquiries</h3>
        <p className="mb-4">For general inquiries about the Services or these Terms, please contact us at:</p>
        <p className="mb-1">Financial Planner AI, LLC</p>
        <p className="mb-4">rpc@financialplanner-ai.com</p>

        <h3 className="text-lg font-semibold mt-4 mb-2">17.2 Legal Notices</h3>
        <p className="mb-4">For legal notices, please contact us at:</p>
        <p className="mb-1">Financial Planner AI, LLC</p>
        <p className="mb-1">Attn: Legal Matter</p>
        <p className="mb-1">155 Glendale Drive</p>
        <p className="mb-1">Freehold, NJ 07728</p>
        <p>rpc@financialplanner-ai.com</p>
      </section>

      <div className="text-center text-sm text-gray-500 mt-12 pt-8 border-t">
        <p>Last Updated: March 21, 2025</p>
        <p>© 2025 Financial Planner AI, LLC. All rights reserved.</p>
      </div>
    </LegalPagesWrapper>
  )
}

